## NumPy Intro

- numpy is python's package for doing math that is more advanced than +-*/

- This includes special functions like cosine, exponential, sqrt, ...

- On top of this we can use numpy to generate samples from many types of random variables

- numpy also has a powerful data type to define vectors, matrices, and tensors

- With these data types numpy also allows us to do linear algebra - matrix multiplication and matrix-vector solutions

## First step of using numpy

In [1]:
# the first step of using numpy is to tell python to use it
import numpy as np

In [2]:
print(np.cos(np.pi))
print(np.sqrt(1.21))
print(np.log(np.exp(5.2)))

-1.0
1.1
5.2


## Array and Matrix

### Array

- An array is a special variable that can hold more than one value at a time. Both the list and array look similar but one major difference is that an array is optimized for arithmetical computations.

In [3]:
Arr = np.array([1,2,3])
Arr

array([1, 2, 3])

### Matrix
- Matrix is a 2-D (2-Dimentional array). It has both rows and columns. The horizontal arrangement of data are rows and the vertical arrangement of data are columns.

In [4]:
Mat=np.array([[1,2,3,1],[4,5,6,4],[7,8,9,7]]) # This code will create a atrix of 3 rows and 4 columns
Mat

array([[1, 2, 3, 1],
       [4, 5, 6, 4],
       [7, 8, 9, 7]])

## Creating numpy arrays

### By converting lists

In [5]:
# we can create numpy arrays by converting lists
# this is a vector
vec = np.array([1,2,3])
print(vec)

[1 2 3]


### By converting lists of lists

In [6]:
# we can create matrices by converting lists of lists
mat = np.array([[1,2,1],[4,5,9],[1,8,9]])
print('')
print(mat)
print('')
print(mat.T)


[[1 2 1]
 [4 5 9]
 [1 8 9]]

[[1 4 1]
 [2 5 8]
 [1 9 9]]


### By using arange

In [7]:
# there are lots of other ways to create numpy arrays
vec2 = np.arange(0,15)
print(vec2)
print('')
vec3 = np.arange(3,21,6)
print(vec3)


[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]

[ 3  9 15]


### By using linspace

In [8]:
vec4 = np.linspace(0,5,10)
print(vec4)

[0.         0.55555556 1.11111111 1.66666667 2.22222222 2.77777778
 3.33333333 3.88888889 4.44444444 5.        ]


### By using reshape

In [9]:
vec4_reshaped = vec4.reshape(5,2)
print(vec4_reshaped)

[[0.         0.55555556]
 [1.11111111 1.66666667]
 [2.22222222 2.77777778]
 [3.33333333 3.88888889]
 [4.44444444 5.        ]]


### np.zeros, np.ones, np.eye

In [10]:
mat2 = np.zeros([5,3])
print(mat2)
mat3 = np.ones((3,5))
print('')
print(mat3)
mat4 = np.eye(5)
print('')
print(mat4)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


## +-*/ on arrays

In [11]:
# we can +-*/ arrays together if they're the right size
vec5 = np.arange(1,6)
vec6 = np.arange(3,8)
print(vec5)
print(vec6)
print(' ')

print ('Addition')
print(vec5+vec6)
print(' ')

print ('Multiplication')

print(vec5*vec6)
print(' ')

print ('Division')

print(1/vec5)
print(np.sqrt(vec6))

[1 2 3 4 5]
[3 4 5 6 7]
 
Addition
[ 4  6  8 10 12]
 
Multiplication
[ 3  8 15 24 35]
 
Division
[1.         0.5        0.33333333 0.25       0.2       ]
[1.73205081 2.         2.23606798 2.44948974 2.64575131]


## Matrix multiplication

In [12]:
# we can do matrix multiplication
print('mat')
print(mat)
print('')

print('vec')
print(vec)
print()


product = np.matmul(mat,vec)
print('product (mat*vec)')
print(product)

mat
[[1 2 1]
 [4 5 9]
 [1 8 9]]

vec
[1 2 3]

product (mat*vec)
[ 8 41 44]


In [13]:
print(np.linalg.solve(mat,product))
print('')
print(np.linalg.inv(mat))

[1. 2. 3.]

[[ 0.5         0.18518519 -0.24074074]
 [ 0.5        -0.14814815  0.09259259]
 [-0.5         0.11111111  0.05555556]]


## Find unique values in an array

In [14]:
# we can find the unique values in an array
vec7 = np.array(['blue','red','orange','purple','purple','orange','Red',6])
print(vec7)
print(np.unique(vec7))

['blue' 'red' 'orange' 'purple' 'purple' 'orange' 'Red' '6']
['6' 'Red' 'blue' 'orange' 'purple' 'red']


## Generate samples of a random variable

In [15]:
# we can also use numpy to generate samples of a random variable
rand_mat = np.random.rand(5,5) # uniform random variable
print(rand_mat)
rand_mat2 = np.random.randn(10,5) # standard normal random variable
print('')
print(rand_mat2)

[[0.71543406 0.16674447 0.02360554 0.69660754 0.15216018]
 [0.13360037 0.22774147 0.30539079 0.20774695 0.40512964]
 [0.28460674 0.1394715  0.4758919  0.07900209 0.54326381]
 [0.35595025 0.89494494 0.71367444 0.21282077 0.06905222]
 [0.75726122 0.44706078 0.807643   0.87830987 0.6275642 ]]

[[ 0.37934123  0.12894339 -0.33425288  0.65028019  2.01744578]
 [-0.98265376  0.61628594  1.25056394  0.80205873  1.325099  ]
 [-1.94713042 -0.21078095 -1.75346061  0.72153832  1.89264425]
 [-0.00998484  1.1194292   1.84081319  0.06616938  0.43476539]
 [ 0.72932567 -0.7303393  -1.47340423  0.19335595  1.21171377]
 [-0.94171147  1.54506869 -1.83479737  1.42781715  0.57566792]
 [ 0.10988111  1.05649339  1.9966051  -0.23952521  0.46960777]
 [-1.02290919  0.73398568 -0.14490921 -0.03206864  0.98044942]
 [-0.57630228 -0.76386456  1.03240174  0.33000724  1.28257994]
 [ 0.20444488  0.13857274 -0.14687774  1.43156974 -0.70357557]]


## Using numpy for statistical tools on array

In [16]:
# we can also use numpy for statistical tools on arrays
print(np.mean(rand_mat))
print(np.std(rand_mat2))

0.41282715008304655
0.9958867780392832


In [17]:
print(np.min(rand_mat))
print(np.max(rand_mat2))

0.023605535336314376
2.0174457829608112


## Accessing numpy entires

### Access single entry

In [18]:
# how do we access entries in a numpy vector
rand_vec = np.random.randn(19)
print(rand_vec)
print(rand_vec[6])

[-0.26744279 -0.62032595 -1.40305233  0.62468644 -0.09198731 -0.16528161
 -1.32662823  0.87982848 -0.27032412  0.76885358  0.77723231  0.95454637
  0.37161604  1.56660033 -1.59591573  0.17264548  0.47944227  0.39430562
 -0.02687859]
-1.3266282303120012


### Access multiple entries

In [19]:
# we can access multiple entries at once using :
print(rand_vec[4:9])

[-0.09198731 -0.16528161 -1.32662823  0.87982848 -0.27032412]


### Access multiple nonconsecutive entries

In [20]:
# we can also access multiple non-consecutive entries using np.arange
print(np.arange(0,15,3))
print(rand_vec[np.arange(0,15,3)])

[ 0  3  6  9 12]
[-0.26744279  0.62468644 -1.32662823  0.76885358  0.37161604]


### Accessing matrices

In [21]:
# what about matrices
print(rand_mat)
print()
print(rand_mat[1][2])
print()
print(rand_mat[1,2])


[[0.71543406 0.16674447 0.02360554 0.69660754 0.15216018]
 [0.13360037 0.22774147 0.30539079 0.20774695 0.40512964]
 [0.28460674 0.1394715  0.4758919  0.07900209 0.54326381]
 [0.35595025 0.89494494 0.71367444 0.21282077 0.06905222]
 [0.75726122 0.44706078 0.807643   0.87830987 0.6275642 ]]

0.305390790137259

0.305390790137259


In [22]:
print(rand_mat[0:2,1:3])

[[0.16674447 0.02360554]
 [0.22774147 0.30539079]]


### Changing values in an array

In [23]:
# let's change some values in an array!
print(rand_vec)
rand_vec[3:5] = 4
print('')
print(rand_vec)
rand_vec[3:5] = [1,2]
print('')
print(rand_vec)

[-0.26744279 -0.62032595 -1.40305233  0.62468644 -0.09198731 -0.16528161
 -1.32662823  0.87982848 -0.27032412  0.76885358  0.77723231  0.95454637
  0.37161604  1.56660033 -1.59591573  0.17264548  0.47944227  0.39430562
 -0.02687859]

[-0.26744279 -0.62032595 -1.40305233  4.          4.         -0.16528161
 -1.32662823  0.87982848 -0.27032412  0.76885358  0.77723231  0.95454637
  0.37161604  1.56660033 -1.59591573  0.17264548  0.47944227  0.39430562
 -0.02687859]

[-0.26744279 -0.62032595 -1.40305233  1.          2.         -0.16528161
 -1.32662823  0.87982848 -0.27032412  0.76885358  0.77723231  0.95454637
  0.37161604  1.56660033 -1.59591573  0.17264548  0.47944227  0.39430562
 -0.02687859]


In [24]:
print(rand_mat)
rand_mat[1:3,3:5] = 0
print('')
print(rand_mat)

[[0.71543406 0.16674447 0.02360554 0.69660754 0.15216018]
 [0.13360037 0.22774147 0.30539079 0.20774695 0.40512964]
 [0.28460674 0.1394715  0.4758919  0.07900209 0.54326381]
 [0.35595025 0.89494494 0.71367444 0.21282077 0.06905222]
 [0.75726122 0.44706078 0.807643   0.87830987 0.6275642 ]]

[[0.71543406 0.16674447 0.02360554 0.69660754 0.15216018]
 [0.13360037 0.22774147 0.30539079 0.         0.        ]
 [0.28460674 0.1394715  0.4758919  0.         0.        ]
 [0.35595025 0.89494494 0.71367444 0.21282077 0.06905222]
 [0.75726122 0.44706078 0.807643   0.87830987 0.6275642 ]]


In [25]:
sub_mat = rand_mat[0:2,0:3]
print(sub_mat)
sub_mat[:] = 3
print(sub_mat)


[[0.71543406 0.16674447 0.02360554]
 [0.13360037 0.22774147 0.30539079]]
[[3. 3. 3.]
 [3. 3. 3.]]


In [26]:
print(rand_mat)

[[3.         3.         3.         0.69660754 0.15216018]
 [3.         3.         3.         0.         0.        ]
 [0.28460674 0.1394715  0.4758919  0.         0.        ]
 [0.35595025 0.89494494 0.71367444 0.21282077 0.06905222]
 [0.75726122 0.44706078 0.807643   0.87830987 0.6275642 ]]


In [27]:
sub_mat2 = rand_mat[0:2,0:3].copy()
sub_mat2[:] = 99
print(sub_mat2)
print(rand_mat)


[[99. 99. 99.]
 [99. 99. 99.]]
[[3.         3.         3.         0.69660754 0.15216018]
 [3.         3.         3.         0.         0.        ]
 [0.28460674 0.1394715  0.4758919  0.         0.        ]
 [0.35595025 0.89494494 0.71367444 0.21282077 0.06905222]
 [0.75726122 0.44706078 0.807643   0.87830987 0.6275642 ]]


### Access entries with logicals

In [28]:
# we can also access entries with logicals
rand_vec = np.random.randn(15)

print(rand_vec)
print(rand_vec>0)
print(rand_vec[rand_vec>0])

[ 1.45541224  0.62134569  0.1106063  -0.59164665 -1.35605894 -0.23894976
  0.42311436  0.73616762 -1.15260085  1.38530895  1.55357256  0.03365846
  2.16821589  0.00517405 -0.62212339]
[ True  True  True False False False  True  True False  True  True  True
  True  True False]
[1.45541224 0.62134569 0.1106063  0.42311436 0.73616762 1.38530895
 1.55357256 0.03365846 2.16821589 0.00517405]


In [29]:
print(rand_mat2)
print(rand_mat2[rand_mat2>0])

[[ 0.37934123  0.12894339 -0.33425288  0.65028019  2.01744578]
 [-0.98265376  0.61628594  1.25056394  0.80205873  1.325099  ]
 [-1.94713042 -0.21078095 -1.75346061  0.72153832  1.89264425]
 [-0.00998484  1.1194292   1.84081319  0.06616938  0.43476539]
 [ 0.72932567 -0.7303393  -1.47340423  0.19335595  1.21171377]
 [-0.94171147  1.54506869 -1.83479737  1.42781715  0.57566792]
 [ 0.10988111  1.05649339  1.9966051  -0.23952521  0.46960777]
 [-1.02290919  0.73398568 -0.14490921 -0.03206864  0.98044942]
 [-0.57630228 -0.76386456  1.03240174  0.33000724  1.28257994]
 [ 0.20444488  0.13857274 -0.14687774  1.43156974 -0.70357557]]
[0.37934123 0.12894339 0.65028019 2.01744578 0.61628594 1.25056394
 0.80205873 1.325099   0.72153832 1.89264425 1.1194292  1.84081319
 0.06616938 0.43476539 0.72932567 0.19335595 1.21171377 1.54506869
 1.42781715 0.57566792 0.10988111 1.05649339 1.9966051  0.46960777
 0.73398568 0.98044942 1.03240174 0.33000724 1.28257994 0.20444488
 0.13857274 1.43156974]


In [30]:
print(rand_vec)
print('')
rand_vec[rand_vec>0.5] = -5
print(rand_vec)

[ 1.45541224  0.62134569  0.1106063  -0.59164665 -1.35605894 -0.23894976
  0.42311436  0.73616762 -1.15260085  1.38530895  1.55357256  0.03365846
  2.16821589  0.00517405 -0.62212339]

[-5.         -5.          0.1106063  -0.59164665 -1.35605894 -0.23894976
  0.42311436 -5.         -1.15260085 -5.         -5.          0.03365846
 -5.          0.00517405 -0.62212339]


## Saving and loading numpy arrays

In [31]:
# let's save some arrays on the disk for use later!
np.save('saved_file_name',rand_mat2)


In [32]:
np.savez('zipped_file_name',rand_mat=rand_mat,rand_mat2=rand_mat2)

In [33]:
# now let's load it
loaded_vec = np.load('saved_file_name.npy')
loaded_zip = np.load('zipped_file_name.npz')

print(loaded_vec)
print('')
print(loaded_zip)

[[ 0.37934123  0.12894339 -0.33425288  0.65028019  2.01744578]
 [-0.98265376  0.61628594  1.25056394  0.80205873  1.325099  ]
 [-1.94713042 -0.21078095 -1.75346061  0.72153832  1.89264425]
 [-0.00998484  1.1194292   1.84081319  0.06616938  0.43476539]
 [ 0.72932567 -0.7303393  -1.47340423  0.19335595  1.21171377]
 [-0.94171147  1.54506869 -1.83479737  1.42781715  0.57566792]
 [ 0.10988111  1.05649339  1.9966051  -0.23952521  0.46960777]
 [-1.02290919  0.73398568 -0.14490921 -0.03206864  0.98044942]
 [-0.57630228 -0.76386456  1.03240174  0.33000724  1.28257994]
 [ 0.20444488  0.13857274 -0.14687774  1.43156974 -0.70357557]]



In [34]:
print(loaded_zip['rand_mat'])
print('')
print(loaded_zip['rand_mat2'])

new_array  = loaded_zip['rand_mat']
print(new_array)

[[3.         3.         3.         0.69660754 0.15216018]
 [3.         3.         3.         0.         0.        ]
 [0.28460674 0.1394715  0.4758919  0.         0.        ]
 [0.35595025 0.89494494 0.71367444 0.21282077 0.06905222]
 [0.75726122 0.44706078 0.807643   0.87830987 0.6275642 ]]

[[ 0.37934123  0.12894339 -0.33425288  0.65028019  2.01744578]
 [-0.98265376  0.61628594  1.25056394  0.80205873  1.325099  ]
 [-1.94713042 -0.21078095 -1.75346061  0.72153832  1.89264425]
 [-0.00998484  1.1194292   1.84081319  0.06616938  0.43476539]
 [ 0.72932567 -0.7303393  -1.47340423  0.19335595  1.21171377]
 [-0.94171147  1.54506869 -1.83479737  1.42781715  0.57566792]
 [ 0.10988111  1.05649339  1.9966051  -0.23952521  0.46960777]
 [-1.02290919  0.73398568 -0.14490921 -0.03206864  0.98044942]
 [-0.57630228 -0.76386456  1.03240174  0.33000724  1.28257994]
 [ 0.20444488  0.13857274 -0.14687774  1.43156974 -0.70357557]]
[[3.         3.         3.         0.69660754 0.15216018]
 [3.         3.    

In [35]:
# we can also save/load as text files...but only single variables
np.savetxt('text_file_name.txt',rand_mat,delimiter=',')
rand_mat_txt = np.loadtxt('text_file_name.txt',delimiter=',')
print(rand_mat)
print('')
print(rand_mat_txt)

[[3.         3.         3.         0.69660754 0.15216018]
 [3.         3.         3.         0.         0.        ]
 [0.28460674 0.1394715  0.4758919  0.         0.        ]
 [0.35595025 0.89494494 0.71367444 0.21282077 0.06905222]
 [0.75726122 0.44706078 0.807643   0.87830987 0.6275642 ]]

[[3.         3.         3.         0.69660754 0.15216018]
 [3.         3.         3.         0.         0.        ]
 [0.28460674 0.1394715  0.4758919  0.         0.        ]
 [0.35595025 0.89494494 0.71367444 0.21282077 0.06905222]
 [0.75726122 0.44706078 0.807643   0.87830987 0.6275642 ]]
